version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./downloads:/var/lib/transmission-daemon/downloads/
    expose:
      - "9091"
    ports:
      - "9091:9091"
    tty: true
    command: /bin/bash
    stdin_open: true
